### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nick42d** [nick42d/LawnTrackerApp#1]
- [x] Location picker for Add screen
- [x] Delete old weather when it's not required
- [ ] Confirm network out behaviour
- [ ] Confirm timezone different between location and phone behaviour
- [x] #20
- [x] Utilise Save button on Add screen
- [x] Move locations setting to its own item on drawer (Abandon)
- [x] Implement Settings
- [x] Implement navigation Drawer for settings.
- [x] Settings - Location management
- [x] Settings - Unit of measure. Consider if this should instead be a default for GDD Trackers? Consider that this would affect GDD Trackers, Locations cards, and API fetch.
- [x] Settings - Warning percentage (slider)
- [x] Settings - Light / dark mode
- [x] Settings - API key (and debug mode for loading test key) (Abandon)
- [x] "Add" screen
- [x] Estimated weather
- [x] Add license
- [x] Handle duplicate locations error better.
- [x] Add a few more items to display on View Tracker
- [x] #10
- [x] Better display when snoozed (e.g on card)
- [x] Able to clear snooze status from app
- [x] Remove unnecessary write to state after loading state (when going from bg to fg)
- [x] Implement snooze and stop for notifications
- [x] Remove need for location permissions
- [x] Improve notification text
- [x] Refactor styles
- [x] Add title to GDD Graph :smile: 
- [x] Estimate up to date target is met (with safety to prevent massive compute)
- [x] #3
- [x] Icon for notifications
- [x] Non GDD cards to also colorize when target close/exceeded
- [x] Update stored state when running background task
- [x] Add API version to stored data
- [x] Deselect search bar once a location has been selected
- [x] Loading indicator for search bar on Add Locations screen
- [x] Notifications to open relevant screen on app
- [x] Check project is GPL ready - images and API use
- [x] Add icon for notifications
- [x] Neaten right hand side icons on trackers
- [x] Improve performance when loading View Gdd Tracker
- [x] Display custom labels when selecting an item on the chart.
- [x] Fix forecasts overlapping with history when adding new weather
- [x] Add dynamic weather icons to Weather screen, check licensing for this.
- [x] Refresh weather on load
- [x] Prevent adding duplicate locations and potentially trackers
- [x] #12
- [x] Add day/night for dynamic weather icons
- [x] Refresh Locations automatically when adding a new one.
- [x] Colourize card total GDD instead of entire card
- [x] Complete Weather screen (add forecast and estimates, allow location selection)
- [x] Add direct entry and view of latitude and longitude on AddLocation screen.
- [x] Improve add locations - navigation / zoom, current location, and initial pin drop
- [x] Add pause / stop button for trackers.
- [x] Better center pin drop on AddLocation screen
- [x] Add screen to view individual locations weather
- [x] Add a loading splash screen
- [x] Local storage of state (and debug mode for loading test data)
- [x] Confirm popup for Refresh or Delete
- [x] Projected completion dates
- [x] Add new locations from "Add" screen
- [x] When adding new locations from "Add" screen, return to same screen.
- [x] #7
- [x] Add openmeteo attribution
- [x] App knowledge base
- [x] Allow edit from View screen
- [x] #9
- [x] #4
- [x] Background task to check if notifications are ready
- [x] Change to new API
- [x] Fix target line on View screen
- [x] #6
- [x] Persist state locally
- [x] #5
- [x] Rename project
- [x] Add other types of trackers (e.g fert). Example types - duration triggered (triggers once duration exceeded), date triggered (triggers once date reached)
